version: '3'

services:
  nginx:
    image: nginx:alpine-slim
    ports:
      - 80:80
    volumes:
      #- "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
    networks:
      - nginx-app
    depends_on:
      - lavagna-app

  lavagna-app:
    image: ${image_updtaed_name}
    networks:
     - app-db
     - nginx-app
    depends_on:
      mysql_db:
        condition: service_healthy
  memcached:  
    image: memcached:1.6.18
    command: ["-m", "11211"]  
    ports:  
    - "11211:11211"   
    restart: always 


networks:
  nginx-app: