name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      run: git clone https://github.com/dvir-pashut/TED-search.git
    - name: Set JDK
      run: export JAVA_HOME=$(ls -d /usr/lib/jvm/java-8-openjdk-amd64)
    - name: Build
      run: |
        cd TED-search
        cd app
        mvn clean install
